
[Energy_Capacity]
	#Range: 1 ~ 9000000000000000000
	spiritedCap = 1
	#Range: 1 ~ 9000000000000000000
	blazingCap = 1
	#Range: 1 ~ 9000000000000000000
	basicCap = 1
	#Range: 1 ~ 9000000000000000000
	nioticCap = 1
	#Range: 1 ~ 9000000000000000000
	nitroCap = 1
	#Range: 1 ~ 9000000000000000000
	hardenedCap = 1
	#Range: 1 ~ 9000000000000000000
	starterCap = 1

[Energy_Transfer]
	#Range: 1 ~ 9000000000000000000
	spiritedTransfer = 90000
	#Range: 1 ~ 9000000000000000000
	starterTransfer = 100
	#Range: 1 ~ 9000000000000000000
	basicTransfer = 1400
	#Range: 1 ~ 9000000000000000000
	hardenedTransfer = 5000
	#Range: 1 ~ 9000000000000000000
	nioticTransfer = 40000
	#Range: 1 ~ 9000000000000000000
	blazingTransfer = 18000
	#Range: 1 ~ 9000000000000000000
	nitroTransfer = 200000

[Channels]
	#Range: 1 ~ 16
	hardenedChannels = 4
	#Range: 1 ~ 16
	basicChannels = 2
	#Range: 1 ~ 16
	spiritedChannels = 12
	#Range: 1 ~ 16
	starterChannels = 1
	#Range: 1 ~ 16
	nioticChannels = 9
	#Range: 1 ~ 16
	blazingChannels = 6
	#Range: 1 ~ 16
	nitroChannels = 16

