
#Mekanism Generators Config. This config is synced between server and client.
[generators]
	#Amount of energy in Joules the Bio Generator produces per tick.
	bioGeneration = "350"
	#Affects the Injection Rate, Max Temp, and Ignition Temp.
	energyPerFusionFuel = "5000000"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	solarGeneration = "50"
	#Peak output for the Advanced Solar Generator. Note: It can go higher than this value in some extreme environments.
	advancedSolarGeneration = "300"

	#Heat Generator Settings
	[generators.heat_generator]
		#Amount of energy in Joules the Heat Generator produces per tick. (heatGenerationLava * heatGenerationLava) + heatGenerationNether
		heatGeneration = "200"
		#Multiplier of effectiveness of Lava in the Heat Generator.
		heatGenerationLava = "30"
		#Add this amount of Joules to the energy produced by a heat generator if it is in the Nether.
		heatGenerationNether = "100"

	#Turbine Settings
	[generators.turbine]
		#The number of blades on each turbine coil per blade applied.
		turbineBladesPerCoil = 4
		#The rate at which steam is vented into the turbine.
		turbineVentGasFlow = 32000.0
		#The rate at which steam is dispersed into the turbine.
		turbineDisperserGasFlow = 1280.0
		#The rate at which steam is condensed in the turbine.
		condenserRate = 64000

	#Wind Generator Settings
	[generators.wind_generator]
		#Minimum base generation value of the Wind Generator.
		windGenerationMin = "60"
		#Maximum base generation value of the Wind Generator.
		windGenerationMax = "480"
		#The minimum Y value that affects the Wind Generators Power generation.
		windGenerationMinY = 24
		#The maximum Y value that affects the Wind Generators Power generation.
		windGenerationMaxY = 255
		#The list of dimension ids that the Wind Generator will not generate power in.
		windGenerationDimBlacklist = []

	#Hohlraum Settings
	[generators.hohlraum]
		#Hohlraum capacity in mB.
		#Range: 1 ~ 9223372036854775807
		maxGas = 10
		#Amount of DT-Fuel Hohlraum can accept per tick.
		#Range: 1 ~ 9223372036854775807
		fillRate = 1

