
#General Config. This config is synced from server to client.
[general]
	#Log Mekanism packet names. Debug setting.
	logPackets = false
	#Disable to make the anchor upgrade not do anything.
	allowChunkloading = true
	#How many ticks must pass until a block's active state is synced with the client, if it has been rapidly changing.
	blockDeactivationDelay = 100
	#Any mod ids added to this list will not be able to have any of their blocks, picked up by the cardboard box.
	cardboardModBlacklist = []
	#Add filled creative gas tanks to creative/JEI.
	prefilledGasTanks = true
	#Allow right clicking on Cables/Pipes/Tubes with alloys to upgrade the tier.
	transmitterAlloyUpgrade = true
	#Base factor for working out machine performance with upgrades - UpgradeModifier * (UpgradesInstalled/UpgradesPossible).
	#Range: > 1
	maxUpgradeMultiplier = 10
	#How much Boiler heat is immediately usable to convert water to steam.
	boilerWaterConductivity = 0.7
	#Amount of heat produced per fuel tick of a fuel's burn time in the Fuelwood Heater.
	heatPerFuelTick = 400.0
	#How much heat energy is created from one Joule of regular energy in the Resistive Heater.
	#Range: 0.0 ~ 1.0
	resistiveHeaterEfficiency = 0.6
	#Amount of heat each Boiler heating element produces.
	superheatingHeatTransfer = 512000.0
	#Displayed temperature unit in Mekanism GUIs.
	#Allowed Values: K, C, R, F, STP
	temperatureUnit = "K"

	#Energy Conversion Rate Settings
	[general.energy_conversion]
		#Disables IC2 power integration. Requires world restart (server-side option in SMP).
		blacklistIC2 = false
		#Conversion multiplier from EU to Joules (EU * JoulesToEU = Joules)
		JoulesToEU = "10"
		#Conversion multiplier from Joules to EU (Joules * EUToJoules = EU)
		EUToJoules = "0.1000"
		#Disables Forge Energy (FE,RF,IF,uF,CF) power integration. Requires world restart (server-side option in SMP).
		blacklistForge = false
		#Conversion multiplier from Forge Energy to Joules (FE * JoulesToForge = Joules)
		JoulesToForge = "2.5000"
		#Conversion multiplier from Joules to Forge Energy (Joules * ForgeToJoules = FE)
		ForgeToJoules = "0.4000"
		#How much energy is produced per mB of Hydrogen, also affects Electrolytic Separator usage, Ethylene burn rate and Gas generator energy capacity.
		HydrogenEnergyDensity = "200"
		#Burn time for Ethylene (1mB hydrogen + 2*bioFuel/tick*200ticks/100mB * 20x efficiency bonus).
		EthyleneBurnTime = 40
		#Maximum Joules per mB of Steam. Also affects Thermoelectric Boiler.
		maxEnergyPerSteam = "10"
		#Displayed energy type in Mekanism GUIs.
		#Allowed Values: J, FE, EU
		energyType = "FE"

	#Digital Miner Settings
	[general.digital_miner]
		#Energy multiplier for using silk touch mode with the Digital Miner.
		silkMultiplier = 6
		#Maximum radius in blocks that the Digital Miner can reach. (Increasing this may have negative effects on stability and/or performance. We strongly recommend you leave it at the default value).
		#Range: > 1
		maxRadius = 32
		#Number of ticks required to mine a single block with a Digital Miner (without any upgrades).
		#Range: > 1
		ticksPerMine = 80

	#Laser Settings
	[general.laser]
		#If enabled, lasers can break blocks and the flamethrower starts fires.
		aestheticWorldDamage = true
		#How far (in blocks) a laser can travel.
		range = 64
		#Energy needed to destroy or attract blocks with a Laser (per block hardness level).
		energyNeededPerHardness = "100000"

	#Pump Settings
	[general.pump]
		#Maximum block distance to pull fluid from for the Electric Pump.
		maxPumpRange = 80
		#If enabled makes Water and Heavy Water blocks be removed from the world on pump.
		pumpWaterSources = false
		#Fluidic Plenisher stops after this many blocks.
		maxPlenisherNodes = 4000

	#Quantum Entangloporter Settings
	[general.quantum_entangloporter]
		#Maximum energy buffer (Mekanism Joules) of an Entangoloporter frequency - i.e. the maximum transfer per tick per frequency. Default is ultimate tier energy cube capacity.
		energyBuffer = "128000000"
		#Maximum fluid buffer (mb) of an Entangoloporter frequency - i.e. the maximum transfer per tick per frequency. Default is ultimate tier tank capacity.
		#Range: > 1
		fluidBuffer = 112000
		#Maximum gas buffer (mb) of an Entangoloporter frequency - i.e. the maximum transfer per tick per frequency. Default is ultimate tier tank capacity.
		#Range: 1 ~ 9223372036854775807
		gasBuffer = 512000

	#Block security/protection Settings
	[general.security]
		#Enable the security system for players to prevent others from accessing their machines. Does NOT affect Frequencies.
		allowProtection = true
		#Ops can bypass the block security restrictions if enabled.
		opsBypassRestrictions = false

	#Thermal Evaporation Plant Settings
	[general.thermal_evaporation]
		#Thermal Evaporation Tower heat loss per tick.
		heatDissipation = 0.02
		#Temperature to amount produced ratio for Thermal Evaporation Tower.
		tempMultiplier = 0.1
		#Heat to absorb per Solar Panel array of Thermal Evaporation Tower.
		solarMultiplier = 0.2
		#Heat capacity of Thermal Evaporation Tower layers (increases amount of energy needed to increase temperature).
		heatCapacity = 100.0

