#Amount of energy in Joules the Bio Generator produces per tick.
#Range: 0.0 ~ 1.7976931348623157E308
bioGeneration = 350.0
#Affects the Injection Rate, Max Temp, and Ignition Temp.
#Range: 0.0 ~ 1.7976931348623157E308
energyPerFusionFuel = 5000000.0
#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
#Range: 0.0 ~ 1.7976931348623157E308
solarGeneration = 50.0
#Peak output for the Advanced Solar Generator. Note: It can go higher than this value in some extreme environments.
#Range: 0.0 ~ 1.7976931348623157E308
advancedSolarGeneration = 300.0

#Heat Generator Settings
[heat_generator]
	#Amount of energy in Joules the Heat Generator produces per tick. (heatGenerationLava * heatGenerationLava) + heatGenerationNether
	#Range: 0.0 ~ 1.7976931348623157E308
	heatGeneration = 150.0
	#Multiplier of effectiveness of Lava in the Heat Generator.
	#Range: 0.0 ~ 1.7976931348623157E308
	heatGenerationLava = 5.0
	#Add this amount of Joules to the energy produced by a heat generator if it is in the Nether.
	#Range: 0.0 ~ 1.7976931348623157E308
	heatGenerationNether = 100.0

#Turbine Settings
[turbine]
	#The number of blades on each turbine coil per blade applied.
	turbineBladesPerCoil = 4
	#The rate at which steam is vented into the turbine.
	turbineVentGasFlow = 16000.0
	#The rate at which steam is dispersed into the turbine.
	turbineDisperserGasFlow = 640.0
	#The rate at which steam is condensed in the turbine.
	condenserRate = 32000

#Wind Generator Settings
[wind_generator]
	#Minimum base generation value of the Wind Generator.
	#Range: 0.0 ~ 1.7976931348623157E308
	windGenerationMin = 60.0
	#Maximum base generation value of the Wind Generator.
	#Range: 0.0 ~ 1.7976931348623157E308
	windGenerationMax = 480.0
	#The minimum Y value that affects the Wind Generators Power generation.
	windGenerationMinY = 24
	#The maximum Y value that affects the Wind Generators Power generation.
	windGenerationMaxY = 255
	#The list of dimension ids that the Wind Generator will not generate power in.
	windGenerationDimBlacklist = []

