
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = 50.0
	#Energy per operation tick (Joules).
	osmiumCompressor = 100.0
	#Energy per operation tick (Joules).
	combiner = 50.0
	#Energy per operation tick (Joules).
	crusher = 50.0
	#Energy per operation tick (Joules).
	metallurgicInfuser = 50.0
	#Energy per operation tick (Joules).
	purificationChamber = 200.0
	#Energy per operation tick (Joules).
	energizedSmelter = 50.0
	#Energy per operation tick (Joules).
	digitalMiner = 100.0
	#Energy per operation tick (Joules).
	electricPump = 100.0
	#Energy per operation tick (Joules).
	rotaryCondensentrator = 50.0
	#Energy per operation tick (Joules).
	oxidationChamber = 200.0
	#Energy per operation tick (Joules).
	chemicalInfuser = 200.0
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = 400.0
	#Energy per operation tick (Joules).
	precisionSawmill = 50.0
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = 400.0
	#Energy per operation tick (Joules).
	chemicalWasher = 200.0
	#Energy per operation tick (Joules).
	chemicalCrystallizer = 400.0
	#Energy per operation tick (Joules).
	seismicVibrator = 50.0
	#Energy per operation tick (Joules).
	pressurizedReactionBase = 5.0
	#Energy per operation tick (Joules).
	fluidicPlenisher = 100.0
	#Energy per operation tick (Joules).
	laser = 5000.0
	#Energy per operation tick (Joules).
	formulaicAssemblicator = 100.0
	#Energy needed for one [recipe unit] of heavy water production (Joules).
	heavyWaterElectrolysis = 800.0

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = 1000
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = 10
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = 10000

