
#Tier Config
[tier]

	#Energy Cubes
	[tier.energy_cubes]
		#Maximum number of Joules Basic energy cubes can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		basicStorage = 2000000.0
		#Output rate in Joules of Basic energy cubes.
		#Range: 1.0 ~ 1.7976931348623157E308
		basicOutput = 800.0
		#Maximum number of Joules Advanced energy cubes can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		advancedStorage = 8000000.0
		#Output rate in Joules of Advanced energy cubes.
		#Range: 1.0 ~ 1.7976931348623157E308
		advancedOutput = 3200.0
		#Maximum number of Joules Elite energy cubes can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		eliteStorage = 3.2E7
		#Output rate in Joules of Elite energy cubes.
		#Range: 1.0 ~ 1.7976931348623157E308
		eliteOutput = 12800.0
		#Maximum number of Joules Ultimate energy cubes can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		ultimateStorage = 1.28E8
		#Output rate in Joules of Ultimate energy cubes.
		#Range: 1.0 ~ 1.7976931348623157E308
		ultimateOutput = 51200.0
		#Maximum number of Joules Creative energy cubes can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		creativeStorage = 1.7976931348623157E308
		#Output rate in Joules of Creative energy cubes.
		#Range: 1.0 ~ 1.7976931348623157E308
		creativeOutput = 1.7976931348623157E308

	#Fluid Tanks
	[tier.fluid_tanks]
		#Storage size of Basic fluid tanks in mB.
		#Range: > 1
		basicStorage = 14000
		#Output rate of Basic fluid tanks in mB.
		#Range: > 1
		basicOutput = 400
		#Storage size of Advanced fluid tanks in mB.
		#Range: > 1
		advancedStorage = 28000
		#Output rate of Advanced fluid tanks in mB.
		#Range: > 1
		advancedOutput = 800
		#Storage size of Elite fluid tanks in mB.
		#Range: > 1
		eliteStorage = 56000
		#Output rate of Elite fluid tanks in mB.
		#Range: > 1
		eliteOutput = 1600
		#Storage size of Ultimate fluid tanks in mB.
		#Range: > 1
		ultimateStorage = 112000
		#Output rate of Ultimate fluid tanks in mB.
		#Range: > 1
		ultimateOutput = 3200
		#Storage size of Creative fluid tanks in mB.
		#Range: > 1
		creativeStorage = 2147483647
		#Output rate of Creative fluid tanks in mB.
		#Range: > 1
		creativeOutput = 1073741823

	#Gas Tanks
	[tier.gas_tanks]
		#Storage size of Basic gas tanks in mB.
		#Range: > 1
		basicStorage = 64000
		#Output rate of Basic gas tanks in mB.
		#Range: > 1
		basicOutput = 256
		#Storage size of Advanced gas tanks in mB.
		#Range: > 1
		advancedStorage = 128000
		#Output rate of Advanced gas tanks in mB.
		#Range: > 1
		advancedOutput = 512
		#Storage size of Elite gas tanks in mB.
		#Range: > 1
		eliteStorage = 256000
		#Output rate of Elite gas tanks in mB.
		#Range: > 1
		eliteOutput = 1028
		#Storage size of Ultimate gas tanks in mB.
		#Range: > 1
		ultimateStorage = 512000
		#Output rate of Ultimate gas tanks in mB.
		#Range: > 1
		ultimateOutput = 2056
		#Storage size of Creative gas tanks in mB.
		#Range: > 1
		creativeStorage = 2147483647
		#Output rate of Creative gas tanks in mB.
		#Range: > 1
		creativeOutput = 1073741823

	#Bins
	[tier.bins]
		#The number of items Basic bins can store.
		#Range: > 1
		basicStorage = 4096
		#The number of items Advanced bins can store.
		#Range: > 1
		advancedStorage = 8192
		#The number of items Elite bins can store.
		#Range: > 1
		eliteStorage = 32768
		#The number of items Ultimate bins can store.
		#Range: > 1
		ultimateStorage = 262144
		#The number of items Creative bins can store.
		#Range: > 1
		creativeStorage = 2147483647

	#Induction
	[tier.induction]
		#Maximum number of Joules Basic induction cells can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		basicStorage = 1.0E9
		#Maximum number of Joules Advanced induction cells can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		advancedStorage = 8.0E9
		#Maximum number of Joules Elite induction cells can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		eliteStorage = 6.4E10
		#Maximum number of Joules Ultimate induction cells can store.
		#Range: 1.0 ~ 1.7976931348623157E308
		ultimateStorage = 5.12E11
		#Maximum number of Joules Basic induction providers can output or accept.
		#Range: 1.0 ~ 1.7976931348623157E308
		basicOutput = 64000.0
		#Maximum number of Joules Advanced induction providers can output or accept.
		#Range: 1.0 ~ 1.7976931348623157E308
		advancedOutput = 512000.0
		#Maximum number of Joules Elite induction providers can output or accept.
		#Range: 1.0 ~ 1.7976931348623157E308
		eliteOutput = 4096000.0
		#Maximum number of Joules Ultimate induction providers can output or accept.
		#Range: 1.0 ~ 1.7976931348623157E308
		ultimateOutput = 3.2768E7

	#Transmitters
	[tier.transmitters]

		#Universal Cables
		[tier.transmitters.energy]
			#Internal buffer in Joules of each Basic universal cable.
			#Range: > 1
			basicCapacity = 3200
			#Internal buffer in Joules of each Advanced universal cable.
			#Range: > 1
			advancedCapacity = 12800
			#Internal buffer in Joules of each Elite universal cable.
			#Range: > 1
			eliteCapacity = 64000
			#Internal buffer in Joules of each Ultimate universal cable.
			#Range: > 1
			ultimateCapacity = 320000

		#Mechanical Pipes
		[tier.transmitters.fluid]
			#Capacity of Basic mechanical pipes in mB.
			#Range: > 1
			basicCapacity = 1000
			#Pump rate of Basic mechanical pipes in mB/t.
			#Range: > 1
			basicPullAmount = 100
			#Capacity of Advanced mechanical pipes in mB.
			#Range: > 1
			advancedCapacity = 4000
			#Pump rate of Advanced mechanical pipes in mB/t.
			#Range: > 1
			advancedPullAmount = 400
			#Capacity of Elite mechanical pipes in mB.
			#Range: > 1
			eliteCapacity = 16000
			#Pump rate of Elite mechanical pipes in mB/t.
			#Range: > 1
			elitePullAmount = 1600
			#Capacity of Ultimate mechanical pipes in mB.
			#Range: > 1
			ultimateCapacity = 64000
			#Pump rate of Ultimate mechanical pipes in mB/t.
			#Range: > 1
			ultimatePullAmount = 6400

		#Pressurized Tubes
		[tier.transmitters.gas]
			#Capacity of Basic pressurized tubes in mB.
			#Range: > 1
			basicCapacity = 256
			#Pump rate of Basic pressurized tubes in mB/t.
			#Range: > 1
			basicPullAmount = 64
			#Capacity of Advanced pressurized tubes in mB.
			#Range: > 1
			advancedCapacity = 1024
			#Pump rate of Advanced pressurized tubes in mB/t.
			#Range: > 1
			advancedPullAmount = 256
			#Capacity of Elite pressurized tubes in mB.
			#Range: > 1
			eliteCapacity = 4096
			#Pump rate of Elite pressurized tubes in mB/t.
			#Range: > 1
			elitePullAmount = 1024
			#Capacity of Ultimate pressurized tubes in mB.
			#Range: > 1
			ultimateCapacity = 16384
			#Pump rate of Ultimate pressurized tubes in mB/t.
			#Range: > 1
			ultimatePullAmount = 4096

		#Logistical Transporters
		[tier.transmitters.items]
			#Item throughput rate of Basic logistical transporters in items/s.
			#Range: > 1
			basicPullAmount = 1
			#Five times travel speed of Basic logistical transporter.
			#Range: > 1
			basicSpeed = 5
			#Item throughput rate of Advanced logistical transporters in items/s.
			#Range: > 1
			advancedPullAmount = 16
			#Five times travel speed of Advanced logistical transporter.
			#Range: > 1
			advancedSpeed = 10
			#Item throughput rate of Elite logistical transporters in items/s.
			#Range: > 1
			elitePullAmount = 32
			#Five times travel speed of Elite logistical transporter.
			#Range: > 1
			eliteSpeed = 20
			#Item throughput rate of Ultimate logistical transporters in items/s.
			#Range: > 1
			ultimatePullAmount = 64
			#Five times travel speed of Ultimate logistical transporter.
			#Range: > 1
			ultimateSpeed = 50

		#Thermodynamic Conductors
		[tier.transmitters.heat]
			#Conduction value of Basic thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			basicInverseConduction = 5.0
			#Heat capacity of Basic thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			basicHeatCapacity = 1.0
			#Insulation value of Basic thermodynamic conductor.
			#Range: 1.0 ~ 1.7976931348623157E308
			basicInsulation = 10.0
			#Conduction value of Advanced thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			advancedInverseConduction = 5.0
			#Heat capacity of Advanced thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			advancedHeatCapacity = 1.0
			#Insulation value of Advanced thermodynamic conductor.
			#Range: 1.0 ~ 1.7976931348623157E308
			advancedInsulation = 400.0
			#Conduction value of Elite thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			eliteInverseConduction = 5.0
			#Heat capacity of Elite thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			eliteHeatCapacity = 1.0
			#Insulation value of Elite thermodynamic conductor.
			#Range: 1.0 ~ 1.7976931348623157E308
			eliteInsulation = 8000.0
			#Conduction value of Ultimate thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			ultimateInverseConduction = 5.0
			#Heat capacity of Ultimate thermodynamic conductors.
			#Range: 1.0 ~ 1.7976931348623157E308
			ultimateHeatCapacity = 1.0
			#Insulation value of Ultimate thermodynamic conductor.
			#Range: 1.0 ~ 1.7976931348623157E308
			ultimateInsulation = 100000.0

