
#Mekanism Tools Config. This config is synced from server to client.
[tools]
	#The chance that Mekanism Armor can spawn on mobs.
	#Range: 0.0 ~ 1.0
	mobArmorSpawnRate = 0.03

	# Material Settings for bronze
	[tools.bronze]
		#Attack damage modifier of bronze swords.
		bronzeSwordDamage = 3
		#Attack speed of bronze swords.
		bronzeSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of bronze shovels.
		bronzeShovelDamage = 1.5
		#Attack speed of bronze shovels.
		bronzeShovelAtkSpeed = -3.0
		#Attack damage modifier of bronze axes.
		bronzeAxeDamage = 2.0
		#Attack speed of bronze axes.
		bronzeAxeAtkSpeed = -3.0999999046325684
		#Attack damage modifier of bronze pickaxes.
		bronzePickaxeDamage = 1
		#Attack speed of bronze pickaxes.
		bronzePickaxeAtkSpeed = -2.799999952316284
		#Attack speed of bronze hoes.
		bronzeHoeAtkSpeed = 3.0
		#Maximum durability of bronze tools.
		bronzeToolMaxUses = 800
		#Efficiency of bronze tools.
		bronzeEfficiency = 14.0
		#Harvest level of bronze paxels.
		bronzePaxelHarvestLevel = 3
		#Attack damage modifier of bronze paxels.
		bronzePaxelDamage = 8.0
		#Attack speed of bronze paxels.
		bronzePaxelAtkSpeed = -2.4000000953674316
		#Efficiency of bronze paxels.
		bronzePaxelEfficiency = 16.0
		#Natural enchantability factor of bronze paxels.
		bronzePaxelEnchantability = 14
		#Maximum durability of bronze paxels.
		bronzePaxelMaxUses = 1100
		#Base attack damage of bronze items.
		bronzeAttackDamage = 6.0
		#Harvest level of bronze tools.
		bronzeHarvestLevel = 2
		#Natural enchantability factor of bronze items.
		bronzeEnchantability = 10
		#Base armor toughness value of bronze armor.
		bronzeToughness = 0.0
		#Maximum durability of bronze boots.
		bronzeBootDurability = 455
		#Maximum durability of bronze leggings.
		bronzeLeggingDurability = 525
		#Maximum durability of bronze chestplates.
		bronzeChestplateDurability = 560
		#Maximum durability of bronze helmets.
		bronzeHelmetDurability = 385
		#Protection value of bronze boots.
		bronzeBootArmor = 2
		#Protection value of bronze leggings.
		bronzeLeggingArmor = 5
		#Protection value of bronze chestplates.
		bronzeChestplateArmor = 6
		#Protection value of bronze helmets.
		bronzeHelmetArmor = 3

	# Material Settings for lapis_lazuli
	[tools.lapis_lazuli]
		#Attack damage modifier of lapis_lazuli swords.
		lapis_lazuliSwordDamage = 3
		#Attack speed of lapis_lazuli swords.
		lapis_lazuliSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of lapis_lazuli shovels.
		lapis_lazuliShovelDamage = 1.5
		#Attack speed of lapis_lazuli shovels.
		lapis_lazuliShovelAtkSpeed = -3.0
		#Attack damage modifier of lapis_lazuli axes.
		lapis_lazuliAxeDamage = 6.0
		#Attack speed of lapis_lazuli axes.
		lapis_lazuliAxeAtkSpeed = -3.0999999046325684
		#Attack damage modifier of lapis_lazuli pickaxes.
		lapis_lazuliPickaxeDamage = 1
		#Attack speed of lapis_lazuli pickaxes.
		lapis_lazuliPickaxeAtkSpeed = -2.799999952316284
		#Attack speed of lapis_lazuli hoes.
		lapis_lazuliHoeAtkSpeed = -1.0
		#Maximum durability of lapis_lazuli tools.
		lapis_lazuliToolMaxUses = 200
		#Efficiency of lapis_lazuli tools.
		lapis_lazuliEfficiency = 5.0
		#Harvest level of lapis_lazuli paxels.
		lapis_lazuliPaxelHarvestLevel = 2
		#Attack damage modifier of lapis_lazuli paxels.
		lapis_lazuliPaxelDamage = 6.0
		#Attack speed of lapis_lazuli paxels.
		lapis_lazuliPaxelAtkSpeed = -2.4000000953674316
		#Efficiency of lapis_lazuli paxels.
		lapis_lazuliPaxelEfficiency = 6.0
		#Natural enchantability factor of lapis_lazuli paxels.
		lapis_lazuliPaxelEnchantability = 10
		#Maximum durability of lapis_lazuli paxels.
		lapis_lazuliPaxelMaxUses = 250
		#Base attack damage of lapis_lazuli items.
		lapis_lazuliAttackDamage = 2.0
		#Harvest level of lapis_lazuli tools.
		lapis_lazuliHarvestLevel = 2
		#Natural enchantability factor of lapis_lazuli items.
		lapis_lazuliEnchantability = 8
		#Base armor toughness value of lapis_lazuli armor.
		lapis_lazuliToughness = 0.0
		#Maximum durability of lapis_lazuli boots.
		lapis_lazuliBootDurability = 169
		#Maximum durability of lapis_lazuli leggings.
		lapis_lazuliLeggingDurability = 195
		#Maximum durability of lapis_lazuli chestplates.
		lapis_lazuliChestplateDurability = 208
		#Maximum durability of lapis_lazuli helmets.
		lapis_lazuliHelmetDurability = 143
		#Protection value of lapis_lazuli boots.
		lapis_lazuliBootArmor = 2
		#Protection value of lapis_lazuli leggings.
		lapis_lazuliLeggingArmor = 6
		#Protection value of lapis_lazuli chestplates.
		lapis_lazuliChestplateArmor = 5
		#Protection value of lapis_lazuli helmets.
		lapis_lazuliHelmetArmor = 2

	# Material Settings for osmium
	[tools.osmium]
		#Attack damage modifier of osmium swords.
		osmiumSwordDamage = 3
		#Attack speed of osmium swords.
		osmiumSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of osmium shovels.
		osmiumShovelDamage = 1.5
		#Attack speed of osmium shovels.
		osmiumShovelAtkSpeed = -3.0
		#Attack damage modifier of osmium axes.
		osmiumAxeDamage = 4.0
		#Attack speed of osmium axes.
		osmiumAxeAtkSpeed = -3.0
		#Attack damage modifier of osmium pickaxes.
		osmiumPickaxeDamage = 1
		#Attack speed of osmium pickaxes.
		osmiumPickaxeAtkSpeed = -2.799999952316284
		#Attack speed of osmium hoes.
		osmiumHoeAtkSpeed = 1.0
		#Maximum durability of osmium tools.
		osmiumToolMaxUses = 500
		#Efficiency of osmium tools.
		osmiumEfficiency = 10.0
		#Harvest level of osmium paxels.
		osmiumPaxelHarvestLevel = 3
		#Attack damage modifier of osmium paxels.
		osmiumPaxelDamage = 5.0
		#Attack speed of osmium paxels.
		osmiumPaxelAtkSpeed = -2.4000000953674316
		#Efficiency of osmium paxels.
		osmiumPaxelEfficiency = 12.0
		#Natural enchantability factor of osmium paxels.
		osmiumPaxelEnchantability = 16
		#Maximum durability of osmium paxels.
		osmiumPaxelMaxUses = 700
		#Base attack damage of osmium items.
		osmiumAttackDamage = 4.0
		#Harvest level of osmium tools.
		osmiumHarvestLevel = 2
		#Natural enchantability factor of osmium items.
		osmiumEnchantability = 12
		#Base armor toughness value of osmium armor.
		osmiumToughness = 1.0
		#Maximum durability of osmium boots.
		osmiumBootDurability = 390
		#Maximum durability of osmium leggings.
		osmiumLeggingDurability = 450
		#Maximum durability of osmium chestplates.
		osmiumChestplateDurability = 480
		#Maximum durability of osmium helmets.
		osmiumHelmetDurability = 330
		#Protection value of osmium boots.
		osmiumBootArmor = 3
		#Protection value of osmium leggings.
		osmiumLeggingArmor = 6
		#Protection value of osmium chestplates.
		osmiumChestplateArmor = 5
		#Protection value of osmium helmets.
		osmiumHelmetArmor = 3

	# Material Settings for refined_glowstone
	[tools.refined_glowstone]
		#Attack damage modifier of refined_glowstone swords.
		refined_glowstoneSwordDamage = 3
		#Attack speed of refined_glowstone swords.
		refined_glowstoneSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of refined_glowstone shovels.
		refined_glowstoneShovelDamage = 1.5
		#Attack speed of refined_glowstone shovels.
		refined_glowstoneShovelAtkSpeed = -3.0
		#Attack damage modifier of refined_glowstone axes.
		refined_glowstoneAxeDamage = 3.0
		#Attack speed of refined_glowstone axes.
		refined_glowstoneAxeAtkSpeed = -3.0999999046325684
		#Attack damage modifier of refined_glowstone pickaxes.
		refined_glowstonePickaxeDamage = 1
		#Attack speed of refined_glowstone pickaxes.
		refined_glowstonePickaxeAtkSpeed = -2.799999952316284
		#Attack speed of refined_glowstone hoes.
		refined_glowstoneHoeAtkSpeed = 2.0
		#Maximum durability of refined_glowstone tools.
		refined_glowstoneToolMaxUses = 300
		#Efficiency of refined_glowstone tools.
		refined_glowstoneEfficiency = 14.0
		#Harvest level of refined_glowstone paxels.
		refined_glowstonePaxelHarvestLevel = 3
		#Attack damage modifier of refined_glowstone paxels.
		refined_glowstonePaxelDamage = 4.0
		#Attack speed of refined_glowstone paxels.
		refined_glowstonePaxelAtkSpeed = -2.4000000953674316
		#Efficiency of refined_glowstone paxels.
		refined_glowstonePaxelEfficiency = 18.0
		#Natural enchantability factor of refined_glowstone paxels.
		refined_glowstonePaxelEnchantability = 22
		#Maximum durability of refined_glowstone paxels.
		refined_glowstonePaxelMaxUses = 450
		#Base attack damage of refined_glowstone items.
		refined_glowstoneAttackDamage = 5.0
		#Harvest level of refined_glowstone tools.
		refined_glowstoneHarvestLevel = 2
		#Natural enchantability factor of refined_glowstone items.
		refined_glowstoneEnchantability = 18
		#Base armor toughness value of refined_glowstone armor.
		refined_glowstoneToughness = 0.0
		#Maximum durability of refined_glowstone boots.
		refined_glowstoneBootDurability = 234
		#Maximum durability of refined_glowstone leggings.
		refined_glowstoneLeggingDurability = 270
		#Maximum durability of refined_glowstone chestplates.
		refined_glowstoneChestplateDurability = 288
		#Maximum durability of refined_glowstone helmets.
		refined_glowstoneHelmetDurability = 198
		#Protection value of refined_glowstone boots.
		refined_glowstoneBootArmor = 3
		#Protection value of refined_glowstone leggings.
		refined_glowstoneLeggingArmor = 6
		#Protection value of refined_glowstone chestplates.
		refined_glowstoneChestplateArmor = 7
		#Protection value of refined_glowstone helmets.
		refined_glowstoneHelmetArmor = 3

	# Material Settings for refined_obsidian
	[tools.refined_obsidian]
		#Attack damage modifier of refined_obsidian swords.
		refined_obsidianSwordDamage = 3
		#Attack speed of refined_obsidian swords.
		refined_obsidianSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of refined_obsidian shovels.
		refined_obsidianShovelDamage = 1.5
		#Attack speed of refined_obsidian shovels.
		refined_obsidianShovelAtkSpeed = -3.0
		#Attack damage modifier of refined_obsidian axes.
		refined_obsidianAxeDamage = 2.0
		#Attack speed of refined_obsidian axes.
		refined_obsidianAxeAtkSpeed = -2.0
		#Attack damage modifier of refined_obsidian pickaxes.
		refined_obsidianPickaxeDamage = 1
		#Attack speed of refined_obsidian pickaxes.
		refined_obsidianPickaxeAtkSpeed = -2.799999952316284
		#Attack speed of refined_obsidian hoes.
		refined_obsidianHoeAtkSpeed = 7.0
		#Maximum durability of refined_obsidian tools.
		refined_obsidianToolMaxUses = 2500
		#Efficiency of refined_obsidian tools.
		refined_obsidianEfficiency = 20.0
		#Harvest level of refined_obsidian paxels.
		refined_obsidianPaxelHarvestLevel = 3
		#Attack damage modifier of refined_obsidian paxels.
		refined_obsidianPaxelDamage = 4.0
		#Attack speed of refined_obsidian paxels.
		refined_obsidianPaxelAtkSpeed = -2.4000000953674316
		#Efficiency of refined_obsidian paxels.
		refined_obsidianPaxelEfficiency = 25.0
		#Natural enchantability factor of refined_obsidian paxels.
		refined_obsidianPaxelEnchantability = 50
		#Maximum durability of refined_obsidian paxels.
		refined_obsidianPaxelMaxUses = 3000
		#Base attack damage of refined_obsidian items.
		refined_obsidianAttackDamage = 10.0
		#Harvest level of refined_obsidian tools.
		refined_obsidianHarvestLevel = 3
		#Natural enchantability factor of refined_obsidian items.
		refined_obsidianEnchantability = 40
		#Base armor toughness value of refined_obsidian armor.
		refined_obsidianToughness = 4.0
		#Maximum durability of refined_obsidian boots.
		refined_obsidianBootDurability = 650
		#Maximum durability of refined_obsidian leggings.
		refined_obsidianLeggingDurability = 750
		#Maximum durability of refined_obsidian chestplates.
		refined_obsidianChestplateDurability = 800
		#Maximum durability of refined_obsidian helmets.
		refined_obsidianHelmetDurability = 550
		#Protection value of refined_obsidian boots.
		refined_obsidianBootArmor = 5
		#Protection value of refined_obsidian leggings.
		refined_obsidianLeggingArmor = 8
		#Protection value of refined_obsidian chestplates.
		refined_obsidianChestplateArmor = 12
		#Protection value of refined_obsidian helmets.
		refined_obsidianHelmetArmor = 5

	# Material Settings for steel
	[tools.steel]
		#Attack damage modifier of steel swords.
		steelSwordDamage = 3
		#Attack speed of steel swords.
		steelSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of steel shovels.
		steelShovelDamage = 1.5
		#Attack speed of steel shovels.
		steelShovelAtkSpeed = -3.0
		#Attack damage modifier of steel axes.
		steelAxeDamage = 4.0
		#Attack speed of steel axes.
		steelAxeAtkSpeed = -3.0
		#Attack damage modifier of steel pickaxes.
		steelPickaxeDamage = 1
		#Attack speed of steel pickaxes.
		steelPickaxeAtkSpeed = -2.799999952316284
		#Attack speed of steel hoes.
		steelHoeAtkSpeed = 1.0
		#Maximum durability of steel tools.
		steelToolMaxUses = 850
		#Efficiency of steel tools.
		steelEfficiency = 14.0
		#Harvest level of steel paxels.
		steelPaxelHarvestLevel = 3
		#Attack damage modifier of steel paxels.
		steelPaxelDamage = 8.0
		#Attack speed of steel paxels.
		steelPaxelAtkSpeed = -2.4000000953674316
		#Efficiency of steel paxels.
		steelPaxelEfficiency = 18.0
		#Natural enchantability factor of steel paxels.
		steelPaxelEnchantability = 14
		#Maximum durability of steel paxels.
		steelPaxelMaxUses = 1250
		#Base attack damage of steel items.
		steelAttackDamage = 4.0
		#Harvest level of steel tools.
		steelHarvestLevel = 3
		#Natural enchantability factor of steel items.
		steelEnchantability = 10
		#Base armor toughness value of steel armor.
		steelToughness = 1.0
		#Maximum durability of steel boots.
		steelBootDurability = 520
		#Maximum durability of steel leggings.
		steelLeggingDurability = 600
		#Maximum durability of steel chestplates.
		steelChestplateDurability = 640
		#Maximum durability of steel helmets.
		steelHelmetDurability = 440
		#Protection value of steel boots.
		steelBootArmor = 3
		#Protection value of steel leggings.
		steelLeggingArmor = 6
		#Protection value of steel chestplates.
		steelChestplateArmor = 7
		#Protection value of steel helmets.
		steelHelmetArmor = 3

