
#Gobber Ore Generation
[gobber2_ore]
	#Chances of Gobber Ore pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	gobberOreChance = 10
	#Maximal height for Gobber Ore pocket generation [0-255, default: 30]
	#Range: 0 ~ 255
	gobberOreMaxHeight = 30
	#Generate Gobber Ore in the world [true / false]
	gobberOreGeneration = true
	#Size of Gobber Ore pockets [0-100, default: 3]
	#Range: 0 ~ 100
	gobberOreSize = 3
	#Minimal height for Gobber Ore pocket generation, [0-255, default: 20]
	#Range: 0 ~ 255
	gobberOReMinHeight = 20

#Gobber Nether Ore Generation
[gobber2_ore_nether]
	#Maximal height for Gobber Nether Ore pocket generation [0-255, default: 50]
	#Range: 0 ~ 255
	gobberOreNetherMaxHeight = 255
	#Minimal height for Gobber Nether Ore pocket generation, [0-255, default: 5]
	#Range: 0 ~ 255
	gobberOreNetherMinHeight = 20
	#Generate Gobber Nether Ore in the world [true / false]
	gobberOreNetherGeneration = true
	#Size of Gobber Nether Ore pockets [0-100, default: 1]
	#Range: 0 ~ 100
	gobberOreNetherSize = 3
	#Chances of Gobber Nether Ore pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	gobberOreNetherChance = 80

#Gobber End Ore Generation
[gobber2_ore_end]
	#Minimal height for Gobber End Ore pocket generation, [0-255, default: 5]
	#Range: 0 ~ 255
	gobberOreEndMinHeight = 0
	#Generate Gobber End Ore in the world [true / false]
	gobberOreEndGeneration = true
	#Size of Gobber End Ore pockets [0-100, default: 5]
	#Range: 0 ~ 100
	gobberOreEndSize = 5
	#Maximal height for Gobber End Ore pocket generation [0-255, default: 50]
	#Range: 0 ~ 255
	gobberOreEndMaxHeight = 255
	#Chances of Gobber End Ore pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	gobberOreEndChance = 80

#Gobber Lucky Block Generation
[gobber2_lucky_block]
	#Size of Gobber Lucky Block pockets [0-100, default: 3]
	#Range: 0 ~ 100
	gobberLuckyBlockSize = 3
	#Chances of Gobber Lucky Block pocket being generated [0-100, default: 20]
	#Range: 0 ~ 100
	gobberLuckyBlockChance = 20
	#Minimal height for Gobber Lucky Block pocket generation, [0-255, default: 1]
	#Range: 0 ~ 255
	gobberLuckyBlockMinHeight = 1
	#Maximal height for Gobber Lucky Block pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberLuckyBlockMaxHeight = 255
	#Generate Gobber Lucky Block in the world [true / false]
	gobberLuckyBlockGeneration = true

