
[armor_values]
	#Trilium Boots Armor Value
	#Range: 0 ~ 8
	trilium_boots_armor_protection = 5
	#Toughness, no decimals
	#Range: 0 ~ 16
	trilium_armor_toughness = 3
	#Trilium Helmet Armor Value
	#Range: 0 ~ 8
	trilium_helmet_armor_protection = 5
	#Trilium Leggings Armor Value
	#Range: 0 ~ 16
	trilium_leggings_armor_protection = 8
	#Durability modifier for the Trilium Armor Set.  Armor durability array:  {5, 8, 10, 5}.  Durability is calculated by modifer x armor piece array value
	#Range: 0 ~ 99999999
	trilium_armor_durability = 56
	#Trilium Chestplate Armor Value
	#Range: 0 ~ 16
	trilium_chestplate_armor_protection = 10

[material_values]
	#Base Durability of the Trilium Tool Set
	#Range: 0 ~ 999999
	trilium_durability = 3600
	#Trilium Enchantability
	#Range: 0 ~ 256
	trilium_enchantability = 20
	#Additional Attack Damage of the Trilium Tool Set.  Note, there are hardcoded scaling values applied internally
	#Range: 0 ~ 100
	trilium_attack_damage = 9
	#Harvest Level of the Trilium Tool Set
	#Range: 0 ~ 7
	trilium_harvest_level = 5

