
#Feature toggles
[cyclic]
	#Disable these items
	sandstoneGear = true
	#Disable these items
	gemObsidianGear = true
	#Disable these items
	emeraldGear = true
	#Disable these items
	netherbrickGear = true
	#Disable this feature
	enchantments = true

	[cyclic.energy]

		[cyclic.energy.anvil]
			#Power to repair one tick of durability
			#Range: 1 ~ 64000
			cost = 750

