
[general]
	#If set to true, the less op Disk values by Reborn Storage will be used for fluid disks.
	retro = false
	#If set to true, 4 extra tiers for item storage will be added. Automatically turns retro mode off.
	higher_disks = false

