
[features]
	#If set true, tools may drop an item when they'll be used.
	extraDrop = true
	#If set true, bone axe and sword make extra damage against special mobs.
	extraDamage = true
	#If set to true paper tools may hurt you.
	damageByPaperTools = true
	#If set true, (wither) skeletons will drop their head with a defined chance if killed with bone axe or sword.
	headDrop = true
	#If set true, using Fiery tools to mine blocks will smelt them.
	autoSmelt = true

	[features.extraDropBool]
		#If set to true the corresponding ore  of the tool drops an additional resource.
		coal = true
		quartz = true
		lapis = true
		emerald = true
		redstone = true

[chances]
	#Sets the chance of an extra drop when using a tool. [Default 5 = 0.5%]
	#Range: 0 ~ 1000
	extraDrop = 5
	#Sets the chance of extra damage when using bone axe or sword on a (wither) skeleton. [Default 200 = 20%]
	#Range: 0 ~ 1000
	extraDamage = 200
	#Sets the chance to take an half heart damage if using paper tools. [Default 100 = 10%]
	#Range: > 0
	damageByPaperTools = 100
	#Sets the chance of an head drop when using bone axe or sword. [Default 50 = 5%]
	#Range: 0 ~ 1000
	headDrop = 50

	[chances.extraDropValue]
		#The chance for dropping an additional resource of their corresponding ore. [Default 500 = 50%]
		#Range: 0 ~ 1000
		coal = 500
		#Range: 0 ~ 1000
		quartz = 500
		#Range: 0 ~ 1000
		lapis = 500
		#Default 1 = 0.1%
		#Range: 0 ~ 1000
		emerald = 1
		#Range: 0 ~ 1000
		redstone = 500

[amounts]
	#The maximum amount of damage. Default: 5 = 2.5 hearts
	#Range: > 0
	maxPaperDamage = 5
	#The minimum amount of damage. Default: 1 = 0.5 hearts
	#Range: > 0
	minPaperDamage = 1

	[amounts.durabilities]
		#Range: > 1
		prismarine = 750
		#Range: > 1
		nether = 280
		#Range: > 1
		obsidian = 2674
		#Range: > 1
		fiery = 750
		#Range: > 1
		quartz = 155
		#The durability of the tools
		#Range: > 1
		bone = 206
		#Range: > 1
		ender = 1859
		#Range: > 1
		glowstone = 193
		#Range: > 1
		slime = 1500
		#Range: > 1
		paper = 13
		#Range: > 1
		coal = 155
		#Range: > 1
		lapis = 193
		#Range: > 1
		emerald = 1859
		#Range: > 1
		redstone = 193

	[amounts.harvestlevels]
		#Range: 0 ~ 4
		prismarine = 3
		#Range: 0 ~ 4
		nether = 1
		#Range: 0 ~ 4
		obsidian = 4
		#Range: 0 ~ 4
		fiery = 3
		#Range: 0 ~ 4
		quartz = 2
		#The harvestlevel of the tools (0 = wood; 1 = stone; 2 = iron; 3 = diamond; 4 = higher)
		#Range: 0 ~ 4
		bone = 1
		#Range: 0 ~ 4
		ender = 3
		#Range: 0 ~ 4
		glowstone = 2
		#Range: 0 ~ 4
		slime = 2
		#Range: 0 ~ 4
		paper = 0
		#Range: 0 ~ 4
		coal = 1
		#Range: 0 ~ 4
		lapis = 2
		#Range: 0 ~ 4
		emerald = 3
		#Range: 0 ~ 4
		redstone = 2

