
["Add New Version"]
	#ModID's of the ServerConfigs that will be deleted when a world with a version lower than this version is loaded the first time. Comma Separated list. (ServerConfig without -server.toml)
	toDelete = "ma-enchants"
	#Version Number. VersionNumbers are simple Integers. Use a number larger than the last version.
	#Range: > 0
	newVersion = 1

["Version History"]
	#Editing these values will not affect any worlds that are already on that version.
	history = ""

