
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 2565927

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

[silents_mechanisms]
	#The byproduct material to output in Silent's Mechanisms' Crusher.
	byproduct = "minecraft:cobblestone"

