
#Bitumen Generation
[bitumen]
	#Size of bitumen pockets [0-100, default: 18]
	#Range: 0 ~ 100
	bitumenSize = 18
	#Minimal height for bitumen pocket generation, [0-255, default: 40]
	#Range: 0 ~ 255
	bitumenMinHeight = 40
	#Generate bitumen in the world [true / false]
	bitumenGeneration = false
	#Chances of bitumen pocket being generated [0-100, default: 25]
	#Range: 0 ~ 100
	bitumenChance = 25
	#Maximal height for bitumen pocket generation [0-255, default: 160]
	#Range: 0 ~ 255
	bitumenMaxHeight = 160

